### PR TITLE
Added the ocdev project get command

### PR DESCRIPTION
**Pull request by mik-dass**
Added the project get command https://github.com/redhat-developer/ocdev/issues/96

### CODE REVIEW

**Comment by mik-dass** [comment]
@TomasTomecek I am working on the `ocdev project <project_name> `command currently. I found out that if the user does oc project <project_name> with the current project_name, the command returns 
`Already on project "<project_name>" on server "https://192.168.42.29:8443"`
Should I replicate this on the ocdev tool too?

**Comment by kadel** [comment]
>I am working on the ocdev project <project_name>command currently.

@mik-dass to switch in between project the command should be `ocdev project set`


> I found out that if the user does oc project <project_name> with the current project_name, the command returns
> Already on project "<project_name>" on server "https://192.168.42.29:8443"

Yes, it should show display message like this indicating that you are already using that project.

**Comment by mik-dass** [comment]
@kadel I have added all the commands and I think it's ready for review. Not sure about the codecov thing though. Should I add tests for it?

**Comment by kadel** [comment]
If you can figure out how to add unit tests to this it would be great. But it is not necessary.
Currently, we don't have a easy way to mock `oc` calls :-(  So adding unit tests might be tricky :-(

**Comment by mik-dass** [comment]
@kadel Ok I will look into it :)

**Comment by kadel** [comment]
Sorry about that @mik-dass , but after #245 was merged you code needs small refactor :-(

I'll merge it as soon as it is done, so you don't end up in the same situation with another PR.

**Comment by mik-dass** [comment]
@kadel Done

**Pull request merged**
