### PR TITLE
Error out if unsupported component type provided

### LINKED ISSUE #88: component create fails in case of no directory provide
looks like it needs to handle the error properly and check required flags argument in place before calling `oc` binary under the hood. The current error message is not intuitive for any new users.

```
$ ./ocdev component create hello
command: [/home/prkumar/.minishift/cache/oc/v3.7.1/linux/oc new-app hello~/tmp/fakeSource753103845 --name hello --labels app.ocdev.developers.redhat.com=myproject,component.ocdev.developers.redhat.com=hello] failed to run:
error: Errors occurred while determining argument types:

hello~/tmp/fakeSource753103845 as a local directory pointing to a Git repository:  stat hello~/tmp/fakeSource753103845: no such file or directory

Errors occurred during resource creation:
error: no match for "hello"

The 'oc new-app' command will match arguments to the following types:

  1. Images tagged into image streams in the current project or the 'openshift' project
     - if you don't specify a tag, we'll add ':latest'
  2. Images in the Docker Hub, on remote registries, or on the local Docker engine
  3. Templates in the current project or the 'openshift' project
  4. Git repository URLs or local paths that point to Git repositories

--allow-missing-images can be used to point to an image that does not exist yet.

See 'oc new-app -h' for examples.
: exit status 1
```

### PR DESCRIPTION
**Pull request by containscafeine**
This commit adds validation for the input component type.
Fix #88

### CODE REVIEW

**Comment by kadel** [comment]
there is a problem with partial matches.

if you run `./ocdev component create a` then the `component.ValidateType` evaluates `a` as a valid type, event it is not.


this is because `oc new-app --search --image-stream` really does seach, and returns even partial matches.
```
▶ oc new-app --search --image-stream a
Image streams (oc new-app --image-stream=<image-stream> [--code=<source>])
-----
jboss-webserver30-tomcat7-openshift
  Project: openshift
  Tracks:  registry.access.redhat.com/jboss-webserver-3/webserver30-tomcat7-openshift
  Tags:    1.1, 1.2, 1.3, 1.3-14, 1.3-15, 1.3-16, latest
jboss-webserver30-tomcat8-openshift
  Project: openshift
  Tracks:  registry.access.redhat.com/jboss-webserver-3/webserver30-tomcat8-openshift
  Tags:    1.1, 1.2, 1.3, 1.3-13, 1.3-14, 1.3-15, latest
jboss-webserver31-tomcat7-openshift
  Project: openshift
  Tracks:  registry.access.redhat.com/jboss-webserver-3/webserver31-tomcat7-openshift
  Tags:    1.0, 1.0-10, 1.0-11, 1.0-12, latest
jboss-webserver31-tomcat8-openshift
  Project: openshift
  Tracks:  registry.access.redhat.com/jboss-webserver-3/webserver31-tomcat8-openshift
  Tags:    1.0, 1.0-10, 1.0-11, 1.0-9, latest
mariadb
  Project: openshift
  Tags:    10.1, latest
redhat-openjdk18-openshift
  Project: openshift
  Tracks:  registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
  Tags:    1.1, 1.1-11, 1.1-12, 1.1-13, latest
```

**Comment by containscafeine** [comment]
Hmm. @kadel how do you suggest we implement this? Should we populate a list of all imageStreams and do an exact search?

**Comment by containscafeine** [comment]
But that will be a pain to obtain from the CLI. Should we start using client-go for some use cases with a sufficient level of abstraction?

**Comment by kadel** [comment]
> Hmm. @kadel how do you suggest we implement this? Should we populate a list of all imageStreams and do an exact search?

it is not that painful -  ` oc get is -n openshift`

But there is a still problem with this validations. What if I have my own builder image?
I'm not sure how to validate that? Not even sure if it shows up in `oc new-app --search`

**Comment by containscafeine** [comment]
Closing because #88 is resolved already, and this PR and obsolete and does not make sense and YOLO!

**Pull request closed without merging**
