### PR TITLE
Modify occlient structure

### PR DESCRIPTION
**Pull request by containscafeine**
This commit modifies occlinet.go file to accept type OcClient as
input. Also adds a utility function to check for the current
project been set by the user.

### CODE REVIEW

**Comment by containscafeine** [comment]
Merge after #21

**Comment by kadel** [comment]
build is failing, `github.com/pkg/errors` is not in vendor

**Comment by containscafeine** [comment]
@kadel weird, works for me, did you rebase to master and try?

**Comment by kadel** [comment]
hmm, I'll re-run travis job

**Comment by kadel** [comment]
oh, sorry, it run before #21 was merged. now it is ok

**Pull request merged**
